### ISSUE TITLE
how to train custom datasets for custom object tracking.

### ISSUE THREAD

**Issue by praneeth0609** [danielgordon10/re3-pytorch#1]
please provide step-by-step procedure to train the custom object datasets. and how to track custom object.
if possible please clarify the bellow quires.
1. where to place the new data-set images.
2. how to do annotations for new datasets.
3. how to do labeling for our custom objects.
Thanks in advance.

**Comment by danielgordon10** [comment]
https://github.com/danielgordon10/re3-pytorch/blob/master/training/datasets/README.md
