### ISSUE TITLE
Multiple object training support

### ISSUE THREAD

**Issue by shivSD** [danielgordon10/re3-pytorch#2]
I see there is support for multiple object tracking in Keras/tensorflow version, but in pytorch version it is missing, does the network or pretrained model support the multiple object tracking ? Please can you throw some high level changes that i need make in re_tracker.py & network.py (pytorch version).

**Comment by danielgordon10** [comment]
There's nothing stopping it from working, I just didn't implement it, but it should be very similar to the TensorFlow version. The network doesn't do multi-object tracking, so the way the multi-object tracker works is to use multiple crops in a batch. Not very sophisticated. I would recommend other projects that actually do multi-object tracking if you want inference that considers multiple objects at once.
