### ISSUE TITLE
Downloading the weights

### ISSUE THREAD

**Issue by fatemehN** [danielgordon10/re3-pytorch#4]
I followed the instructions but I couldn't download the weights. After the following command:
```
$ sh download_weights_large.sh
```
I got this error:
```
File size is 712 MB
download_weights_large.sh: 4: download_weights_large.sh: gdown: not found
tar (child): checkpoints.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```
Any suggestion??

My OS is Ubuntu 18.04, CUDA 9.1

**Comment by fatemehN** [comment]
I downloaded the weights directly by copying and pasting the URL of the .sh file.

**Comment by danielgordon10** [comment]
It looks like you haven't installed gdown (one of the project's requirements).
`pip install gdown` and try again.
