### ISSUE TITLE
download weights

### ISSUE THREAD

**Issue by Ahmed471996** [danielgordon10/re3-pytorch#7]
I'm trying to download the weights but I get the following error 

File size is 712 MB
Permission denied: https://drive.google.com/uc?id=1EmA3fnPh1tQXMsZtsJo3YkGw93Ytz8Hd
Maybe you need to change permission over 'Anyone with the link'?
tar (child): checkpoints.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by danielgordon10** [comment]
The issue has been fixed, though the link has changed.
